import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/src/components/header'
import { getConfigs } from '@/src/services/configs'
import Footer from '@/src/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const {
    config
  } = await getConfigs();

  return (

    <html lang="en">

      <body suppressHydrationWarning={true} className={inter.className}>

        <Header config={config} />

        <div style={{ marginTop: 78 }} />

        {children}

        <Footer config={config} />

      </body>

    </html>

  )

}
